name: study_sns_login
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.2
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  flutter_web_auth: ^0.4.1
  uuid: ^3.0.6
  http: ^0.13.4
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
